//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SnoTrack.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_IMPORT_SERIAL_WELCOME_PAGE  104
#define IDD_IMPORT_SERIAL_DEVICE_PAGE   105
#define IDC_CENTER                      105
#define IDD_IMPORT_SERIAL_COMPLETE_PAGE 106
#define IDC_ZOOM_OUT                    106
#define IDD_IMPORT_SERIAL_PROGRESS_PAGE 107
#define IDC_ZOOM_IN                     107
#define IDD_STARTPAGEVIEW               108
#define IDC_DEFINE_HOTSPOT              108
#define IDD_SIDEBARVIEW                 110
#define IDR_MAINFRAME                   128
#define IDR_SNOTRACKTYPE                129
#define IDB_WATERMARK                   129
#define IDB_IMPORT_SERIAL_WATERMARK     129
#define IDB_HEADER                      130
#define IDD_IMPORT_FILE_PROGRESS        130
#define IDS_IMPORT_SERIAL_CANCELLED_TITLE 130
#define IDB_IMPORT_SERIAL_HEADER        130
#define IDS_IMPORT_SERIAL_PROGRESS_PAGE_TITLE 131
#define IDD_PROPERTIES                  131
#define IDD_TRACKLOG_STATS_PAGE         131
#define IDD_FILE_PROPERTIES_TRACKLOG    131
#define IDR_TIMELINE                    132
#define IDS_IMPORT_SERIAL_SUCCEEDED_TITLE 132
#define IDD_NEW_FILE_WELCOME_PAGE       132
#define IDS_IMPORT_SERIAL_FAILED_TITLE  133
#define IDD_NEW_FILE_COMPLETE_PAGE      133
#define IDB_MAINFRAME32                 134
#define IDS_PROPERTIES_CAPTION          134
#define IDD_NEW_FILE_RESORT_PAGE        134
#define IDS_IMPORT_SERIAL_DEVICE_PAGE_TITLE 135
#define IDB_TIMELINE32                  135
#define IDS_NEW_FILE_WIZARD_CAPTION     136
#define IDB_NEW_FILE_WATERMARK          136
#define IDB_NEW_FILE_HEADER             137
#define IDS_NEW_FILE_RESORT_CAPTION     137
#define IDD_VIEW_OPTIONS                137
#define IDS_IMPORT_SERIAL_WIZARD_CAPTION 138
#define IDS_IMPORT_SERIAL_CANCELLED     139
#define IDD_FILE_PROPERTIES_RESORT      139
#define IDS_IMPORT_SERIAL_FAILED        140
#define IDD_FILE_PROPERTIES_DEVICE      140
#define IDS_IMPORT_SERIAL_SUCCEEDED     141
#define IDD_SELECT_HOTSPOT_ID           141
#define IDR_STARTPAGEVIEW               142
#define IDD_EDIT_PATHS                  142
#define IDS_NEW_FILE_RESORT_TITLE       143
#define IDD_EDIT_PATH                   143
#define IDS_NEW_FILE_RESORT_SUBTITLE    144
#define IDD_WALK_HOTSPOTS               144
#define IDS_NEW_FILE_WELCOME_CAPTION    145
#define IDD_DEFINE_HOTSPOT_GRID         145
#define IDS_NEW_FILE_COMPLETE_CAPTION   146
#define ID_INDICATOR_LON                147
#define ID_INDICATOR_LAT                148
#define ID_INDICATOR_SCALE              149
#define IDS_EMPTY_DATASET               150
#define IDS_START_PAGE_TITLE            151
#define IDS_FAILED_TO_OPEN_TRACKLOG_CSV 152
#define IDS_MEMORY_ALLOCATION_FAILED    153
#define IDS_FAILED_TO_COMPOSE_PATH_TO_UPLOAD_WIZARD 154
#define IDS_FAILED_TO_FIND_UPLOAD_WIZARD 155
#define IDS_FAILED_OPEN_EXPORT_TRACKLOG_CSV 156
#define IDS_FAILED_OPEN_EXPORT_WAYPOINT_CSV 157
#define IDS_EXPIRED                     158
#define IDS_OTHER_RESORT_FILENAME       159
#define IDS_COMMENTS_SIZE               160
#define IDS_LOOKING_FOR_GARMIN          161
#define IDS_DOWNLOADING_TRACKLOG        162
#define IDS_DOWNLOADING_WAYPOINTS       163
#define IDS_CONFIRM_HIDE_ALL_LAYERS     164
#define IDR_ENABLE_DESIGN_MODE          165
#define IDR_DESIGN_MODE                 165
#define IDD_MATCH_PATHS                 166
#define IDB_EVENT_ICONS                 167
#define IDD_EDIT_LIFTS                  168
#define IDD_EDIT_LIFT                   169
#define IDD_EDIT_WAYPOINTS              170
#define IDD_EDIT_LIFT1                  171
#define IDD_EDIT_WAYPOINT               171
#define IDD_SELECT_HOTSPOT_SIZE         172
#define IDD_EDIT_HOTSPOT_NAMES          173
#define IDD_DIALOG1                     174
#define IDC_TITLE                       1000
#define IDC_PROGRESS                    1000
#define IDC_TRACKLOG_PROGRESS           1001
#define IDC_SHOW_ADVANCED_OPTIONS       1002
#define IDC_SERIAL_DEVICES              1002
#define IDC_COMPLETION_MESSAGE          1003
#define IDC_LISTCTRL                    1005
#define IDC_OPEN_FILE                   1006
#define IDC_NEW_PATH                    1006
#define IDC_BROWSE_RESORT_FILE          1006
#define IDC_NEW_FILE                    1007
#define IDC_DELETE_PATH                 1008
#define IDC_COPYRIGHT                   1009
#define IDC_CALC_MAX_LAT                1009
#define IDC_VERSION                     1010
#define IDC_COMPLETION_ICON             1011
#define IDC_TRACKLOG_COUNT              1012
#define IDC_WAYPOINT_COUNT              1013
#define IDC_MIN_LATITUDE                1014
#define IDC_MAX_LONGITUDE               1015
#define IDC_MIN_LONGITUDE               1016
#define IDC_MAX_LATITUDE                1017
#define IDC_MAX_ELEVATION               1018
#define IDC_MIN_ELEVATION               1020
#define IDC_MAX_TIMESTAMP               1021
#define IDC_MIN_TIMESTAMP               1023
#define IDC_WEBSITE_URL                 1024
#define IDC_RESORT_FILE                 1025
#define IDC_COMMENTS                    1026
#define IDC_RESORT                      1027
#define IDC_RESORT_NAME                 1029
#define IDC_PRODUCT_ID                  1034
#define IDC_SOFTWARE_VERSION            1035
#define IDC_PRODUCT_DESCRIPTION         1036
#define IDC_ADDITIONAL_INFORMATION      1038
#define IDC_RESORT_TIMEZONE             1042
#define IDC_CURRENT_ID                  1044
#define IDC_PATH_NAME                   1044
#define IDC_MIN_LON                     1044
#define IDC_MAX_LON                     1045
#define IDC_NEW_ID                      1046
#define IDC_MIN_LAT                     1046
#define IDC_SPIN_ID                     1047
#define IDC_MAX_LAT                     1047
#define IDC_GRID_SPACING                1048
#define IDC_EDIT_PATH                   1049
#define IDC_PATH_HOTSPOTS               1050
#define IDC_PREDEFINED_RESORT           1055
#define IDC_CUSTOM_RESORT               1056
#define IDC_IMAGELIST                   1060
#define IDC_NEW                         1061
#define IDC_EDIT                        1062
#define IDC_DELETE                      1063
#define IDC_TOP_LON                     1065
#define IDC_TOP_LAT                     1066
#define IDC_LIFT_NAME                   1067
#define IDC_BOT_LON                     1068
#define IDC_WAYPOINT_NAME               1068
#define IDC_BOT_LAT                     1069
#define IDC_WAYPOINT_LON                1069
#define IDC_WAYPOINT_LAT                1070
#define IDC_LIST1                       1072
#define IDC_LISTBOX                     1072
#define IDC_PATH_IS_LIFT                1073
#define IDC_HOTSPOT_SIZE                1074
#define IDC_HOTSPOT_SIZE_SPIN           1075
#define IDC_EDIT_NAME                   1077
#define IDC_HOTSPOT_ID                  1079
#define IDC_HOTSPOT_NAME                1080
#define ID_IMPORT_SERIAL                32772
#define ID_IMPORT_TRACKLOGFROMFILE      32773
#define ID_FILE_PROPERTIES              32774
#define ID_VIEW_TRACKLOG                32775
#define ID_TOOLS_PROJECTLAT             32776
#define ID_IMPORT_WAYPOINTSFROMFILE     32777
#define ID_VIEW_ZOOMIN                  32778
#define ID_VIEW_ZOOMOUT                 32779
#define ID_MODE_ZOOMIN                  32782
#define ID_MODE_ZOOMOUT                 32783
#define ID_MODE_CENTER                  32786
#define ID_VIEW_ZOOM                    32792
#define ID_VIEW_ROTATECCW               32797
#define ID_VIEW_ROTATECW                32798
#define ID_FILE_UPLOADFILE              32803
#define ID_EXPORT_TRACKLOGTOFILE        32804
#define ID_EXPORT_WAYPOINTSTOFILE       32805
#define ID_VIEW_OPTIONS                 32806
#define ID_IMPORT_NMEAFROMFILE          32809
#define ID_IMPORT_FROMSNOLOGFILE        32810
#define ID_RESORT_EDIT_LIFTS            32811
#define ID_RESORT_EDIT_WAYPOINTS        32812
#define ID_HOTSPOTS_DEFINEHOTSPOTS      32814
#define ID_HOTSPOTS_SAVEHOTSPOTS        32816
#define ID_HOTSPOTS_LOADHOTSPOTS        32817
#define ID_HOTSPOTS_CLEARHOTSPOTS       32818
#define ID_HOTSPOTS_WALK                32819
#define ID_HOTSPOTS_SELECTID            32820
#define ID_HOTSPOTS_EDITPATHS           32821
#define ID_HOTSPOTS_MATCHPATHS          32822
#define ID_RESORT_OPEN                  32825
#define ID_RESORT_SAVEAS                32827
#define ID_RESORT_CLOSE                 32828
#define ID_RESORT_NEW                   32829
#define ID_RESORT_HIDEMATCHEDPATHS      32831
#define ID_RESORT_HIDELIFTS             32832
#define ID_RESORT_SHOWALL               32833
#define ID_RESORT_RECALCULATEROUTES     32834
#define ID_RESORT_HOTSPOTSIZE           32835
#define ID_RESORT_HOTSPOTNAMES          32836
#define ID_VIEW_UNHIDE                  32837
#define ID_VIEW_HIDE                    32838

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        175
#define _APS_NEXT_COMMAND_VALUE         32841
#define _APS_NEXT_CONTROL_VALUE         1081
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
