/* version.h
 */

#define FILEVERSION_MAJOR		0
#define FILEVERSION_MINOR		0
#define FILEVERSION_REVISION	69

#define PRODUCTVERSION_MAJOR	0
#define PRODUCTVERSION_MINOR	0
#define PRODUCTVERSION_REVISION	69

#define STRIZE(x) STRIZE2(x)
#define STRIZE2(x) #x

#define FILEVERSION_STRING STRIZE(FILEVERSION_MAJOR) "." STRIZE(FILEVERSION_MINOR) "." STRIZE(FILEVERSION_REVISION) ".0"
#define PRODUCTVERSION_STRING STRIZE(PRODUCTVERSION_MAJOR) "." STRIZE(PRODUCTVERSION_MINOR) "." STRIZE(PRODUCTVERSION_REVISION) ".0"
